services:
  - type: web
    name: riftdle-server
    runtime: node
    plan: free
    rootDir: server
    buildCommand: cd .. && npm install && npm run build:render && cd server && npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
